// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getServerSupabaseSecretKey(): string | undefined {
  const legacy = process.env["SUPABASE_SERVICE_ROLE_KEY"];
  if (legacy) return legacy;

  const modern = process.env["SUPABASE_SECRET_KEY"] ?? process.env["SUPABASE_SERVICE_KEY"];
  if (modern) return modern;

  const grouped = process.env["SUPABASE_SECRET_KEYS"];
  if (grouped) {
    try {
      const parsed = JSON.parse(grouped) as Record<string, unknown>;
      const defaultKey = parsed["default"];
      if (typeof defaultKey === "string" && defaultKey) return defaultKey;
      const firstKey = Object.values(parsed).find((value) => typeof value === "string" && value);
      if (typeof firstKey === "string") return firstKey;
    } catch {
      // Ignore malformed grouped secrets and report a normal configuration error below.
    }
  }

  return undefined;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env["SUPABASE_URL"] ?? process.env["VITE_SUPABASE_URL"];
  const SUPABASE_SECRET_KEY = getServerSupabaseSecretKey();

  if (!SUPABASE_URL || !SUPABASE_SECRET_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SECRET_KEY
        ? ["SUPABASE_SECRET_KEY (or SUPABASE_SERVICE_ROLE_KEY)"]
        : []),
    ];
    const message = `Missing Supabase server configuration: ${missing.join(", ")}. Connect Supabase and add the server secret key in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SECRET_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SECRET_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
